import { Inter } from "next/font/google";
import StoreProvider from "../redux/StoreProvider";
import React from "react";
import { Toaster } from "../components/ui/toaster";

import "../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "in-n-out",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <React.StrictMode>
      <StoreProvider>
        <html>
          <body className={inter.className}>
            <Toaster />
            {children}
          </body>
        </html>
      </StoreProvider>
    </React.StrictMode>
  );
}
