import { Inter } from "next/font/google";
import StoreProvider from "@/redux/StoreProvider";
import { NextAuthProvider } from "./NextAuthProvider";
import { ChakraProvider } from "@chakra-ui/react";
import theme from "./theme";
import React from "react";

// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "in-n-out",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <React.StrictMode>
      <StoreProvider>
        <NextAuthProvider>
          <html>
            <body>
              <ChakraProvider theme={theme}>{children}</ChakraProvider>
            </body>
          </html>
        </NextAuthProvider>
      </StoreProvider>
    </React.StrictMode>
  );
}
